{
    "_RejCode":"000000",
    "List":[
        {
            "PayeeNo":"_P183319",
            "PayeeAcName":"他行管莹",
            "PayeeType":"P",
            "PayeeTypeName":"网银快汇",
            "PayeeBankName":"招商银行",
            "PayeeAcNo":"6225882302363327",
            "PayeeBankId":"308584000013",
            "ProvinceCode":"",
            "ProvinceName":"",
            "CityCode":"",
            "CityName":"",
            "PayeeDeptId":"",
            "PayeeDeptName":"",
            "Mobile":"",
            "PayeeClearBankId":"308584000013",
            "UnionDeptId":"",
            "UnionDeptName":"",
            "SysFlag":""
        }
        ,
        {
            "PayeeNo":"_P158237",
            "PayeeAcName":"他行魏安平",
            "PayeeType":"P",
            "PayeeTypeName":"网银快汇",
            "PayeeBankName":"中国银行",
            "PayeeAcNo":"6216680500000194367",
            "PayeeBankId":"104100000004",
            "ProvinceCode":"",
            "ProvinceName":"",
            "CityCode":"",
            "CityName":"",
            "PayeeDeptId":"",
            "PayeeDeptName":"",
            "Mobile":"",
            "PayeeClearBankId":"104100000004",
            "UnionDeptId":"",
            "UnionDeptName":"",
            "SysFlag":""
        }
        ,
        {
            "PayeeNo":"_P163816",
            "PayeeAcName":"他行程莹莹",
            "PayeeType":"P",
            "PayeeTypeName":"网银快汇",
            "PayeeBankName":"广发银行",
            "PayeeAcNo":"6225683933000381668",
            "PayeeBankId":"306581000003",
            "ProvinceCode":"",
            "ProvinceName":"",
            "CityCode":"",
            "CityName":"",
            "PayeeDeptId":"",
            "PayeeDeptName":"",
            "Mobile":"",
            "PayeeClearBankId":"306581000003",
            "UnionDeptId":"",
            "UnionDeptName":"",
            "SysFlag":""
        }
        
    ]
}