{
    "_RejCode":"FIN0000",
    "List":[
        {
            "PayeeAcNo":"收款帐号",
            "PayeeAcName":"收款户名",
            "PayeeBankName":"收款行",
            "PayerCurrency":"捐款币种",
            "Amount":"捐款金额",
            "TransTime":"捐款日期",
            "JnlStatus":"状态"
        },
        {
            "PayeeAcNo":"收款帐号",
            "PayeeAcName":"收款户名",
            "PayeeBankName":"收款行",
            "PayerCurrency":"捐款币种",
            "Amount":"捐款金额",
            "TransTime":"捐款日期",
            "JnlStatus":"状态"
        },
        {
            "PayeeAcNo":"收款帐号",
            "PayeeAcName":"收款户名",
            "PayeeBankName":"收款行",
            "PayerCurrency":"捐款币种",
            "Amount":"捐款金额",
            "TransTime":"捐款日期",
            "JnlStatus":"状态"
        },
        {
            "PayeeAcNo":"收款帐号",
            "PayeeAcName":"收款户名",
            "PayeeBankName":"收款行",
            "PayerCurrency":"捐款币种",
            "Amount":"捐款金额",
            "TransTime":"捐款日期",
            "JnlStatus":"状态"
        }
    ]
}